// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-Jn0cKRic_WpU2XY3NpOnzAtqpDxHN4',
    appId: '1:702865549166:web:e5980abeafa8a0f847437f',
    messagingSenderId: '702865549166',
    projectId: 'smart-villa-prime',
    authDomain: 'smart-villa-prime.firebaseapp.com',
    storageBucket: 'smart-villa-prime.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyzJxWPu5q8_h3J9yv9ZhWClCecivsKs',
    appId: '1:702865549166:android:27195b9425f967d447437f',
    messagingSenderId: '702865549166',
    projectId: 'smart-villa-prime',
    storageBucket: 'smart-villa-prime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4h0f89BL8erIhLZmSmWEZx0y5hoy4Kx0',
    appId: '1:702865549166:ios:d52301f1ac3f907947437f',
    messagingSenderId: '702865549166',
    projectId: 'smart-villa-prime',
    storageBucket: 'smart-villa-prime.firebasestorage.app',
    iosBundleId: 'com.example.smartVillaPrime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4h0f89BL8erIhLZmSmWEZx0y5hoy4Kx0',
    appId: '1:702865549166:ios:d52301f1ac3f907947437f',
    messagingSenderId: '702865549166',
    projectId: 'smart-villa-prime',
    storageBucket: 'smart-villa-prime.firebasestorage.app',
    iosBundleId: 'com.example.smartVillaPrime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE-Jn0cKRic_WpU2XY3NpOnzAtqpDxHN4',
    appId: '1:702865549166:web:b317394f42814b3247437f',
    messagingSenderId: '702865549166',
    projectId: 'smart-villa-prime',
    authDomain: 'smart-villa-prime.firebaseapp.com',
    storageBucket: 'smart-villa-prime.firebasestorage.app',
  );
}
